print("This will decorate your name!")
name = input("What is your name?")
print("<<<", name, ">>>")
print("(((", name, ")))")
print("---", name, "---")
print(":):)", name, ":):)")
print("###", name, "###")
print("+++", name, "+++")
print("~~~", name, "~~~")
print(" ===", name, " ===")