from __future__ import division

print("This will calculate your budget:")
income = int(input("how much do you make a month:"))
rent = int(input("how much do you pay in rent a month:"))
utilities = int(input("How much do you pay for utilities per month:"))
groceries = int(input("How much do you pay for grocieries a month:"))
transport = int(input("How much do you pay for transportation per month:"))
expenses = int(rent + utilities + transport + groceries)
savings = int(income-expenses)
total = (int(income) + int(expenses))
prent = rent/income
putilities = (utilities/income)
ptransport = (transport/income)
pexpenses = (expenses/income)
print("your income is: $", income)
print("your expenses is: $", expenses)
print("your rent is: ", prent*100, "% of your income")
print("your utilities is: ", putilities*100, "% of your income")
print("your transport is: ", ptransport*100, "% of your income")
print("your expenses is: ", pexpenses*100, "% of your income")
print("your expenses is: $", total)
print("Your monthly savings/spending money is: $", savings)